CREATE TABLE USU_USUARIO
(
	USU_ID INTEGER NOT NULL,
	USU_LOGIN VARCHAR(20) NOT NULL,
	USU_SENHA VARCHAR(25) NOT NULL,
	USU_CHANNEL VARCHAR(20) NOT NULL,
	USU_APP VARCHAR(50) NOT NULL,
	PRIMARY KEY (USU_ID)
);

CREATE TABLE PER_PERIODO
(
	PER_ID INTEGER NOT NULL,
	PER_VALOR INTEGER NOT NULL,
	PER_TIPO INTEGER NOT NULL,
	PRIMARY KEY (PER_ID)
);

CREATE TABLE CHN_CONFIG
(
	CHN_ID INTEGER NOT NULL,
	USU_ID INTEGER NOT NULL,
	PER_ID INTEGER NOT NULL,
	CHN_QTD_MAXIMA DOUBLE NOT NULL,
	PRIMARY KEY (USU_ID),
	FOREIGN KEY (USU_ID) REFERENCES USU_USUARIO(USU_ID),
	FOREIGN KEY (PER_ID) REFERENCES PER_PERIODO(PER_ID)
);

COMMIT;